{
 "title": "Kostal Plenticore",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "kWEuroEinspeisung", "label": "€/kWh Einspeisung", "query": "0.1095" },
   { "name": "kWEuroBezug", "label": "€/kWh Netzbezug", "query": "0.2775" }
  ]
 },
 "panels": [
  {
   "title": "Stromfluss",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "select": [
      [
       {
        "params": [
         "Total active power (powermeter)"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Erzeugung",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "select": [
      [
       { "params": [ "Total DC power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Batterie",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "select": [
      [
       {
        "params": [
         "Current battery charge-discharge power"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Verbrauch",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "alias": "Westen / hinten",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "query": "SELECT (last(\"Power DC1\") + last(\"Power DC2\")) FROM \"modbus.HoldingRegister\" WHERE $timeFilter GROUP BY time($__interval*4) fill(null)",
     "select": [
      [
       { "params": [ "Total AC active power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Erzeugung",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "alias": "Westen / hinten",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "query": "SELECT (last(\"Power DC1\") + last(\"Power DC2\")) FROM \"modbus.HoldingRegister\" WHERE $timeFilter GROUP BY time($__interval*4) fill(null)",
     "select": [
      [
       { "params": [ "Power DC1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Batterie Ladezustand",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "select": [
      [
       { "params": [ "Battery current SOC" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hausverbrauch",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "watth",
   "valueName": "current",
   "targets": [
    {
     "alias": "PV",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "select": [
      [
       { "params": [ "Home own consumption from PV" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Batterie",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "select": [
      [
       {
        "params": [
         "Home own consumption from battery"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Netz",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "select": [
      [
       { "params": [ "Home own consumption from grid" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Erzeugung",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "String 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "select": [
      [
       { "params": [ "Power DC1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "String 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "select": [
      [
       { "params": [ "Power DC2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hausverbrauch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Batterie laden",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "query": "SELECT mean(\"Current battery charge-discharge power\") * -1  FROM \"modbus.HoldingRegister\" WHERE \"Current battery charge-discharge power\" < 0 AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       {
        "params": [
         "Current battery charge-discharge power"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "Current battery charge-discharge power",
       "operator": "<",
       "value": "0"
      }
     ]
    },
    {
     "alias": "Batterie entladen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "query": "SELECT mean(\"Current battery charge-discharge power\")  FROM \"modbus.HoldingRegister\" WHERE \"Current battery charge-discharge power\" > 0 AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       {
        "params": [
         "Home own consumption from battery"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Direktverbrauch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "select": [
      [
       { "params": [ "Home own consumption from PV" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Netzbezug",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "select": [
      [
       { "params": [ "Home own consumption from grid" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Netzeinspeisung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "select": [
      [
       {
        "params": [
         "Total active power (powermeter)"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "Total active power (powermeter)",
       "operator": "<",
       "value": "0"
      }
     ]
    }
   ]
  },
  {
   "title": "Verbrauch nach Erzeuger",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "PV",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "select": [
      [
       { "params": [ "Home own consumption from PV" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Speicher",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "select": [
      [
       {
        "params": [
         "Home own consumption from battery"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Netz",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "query": "SELECT mean(\"Home own consumption from grid\") FROM \"modbus.HoldingRegister\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Home own consumption from grid" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Batterie Ladezustand",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Ladezustand",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "select": [
      [
       { "params": [ "Battery current SOC" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Batterie Ladeleistung",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Laden",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "select": [
      [
       {
        "params": [
         "Current battery charge-discharge power"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "Current battery charge-discharge power",
       "operator": "<",
       "value": "0"
      }
     ]
    },
    {
     "alias": "Entladen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "select": [
      [
       {
        "params": [
         "Current battery charge-discharge power"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "Current battery charge-discharge power",
       "operator": ">",
       "value": "0"
      }
     ]
    }
   ]
  },
  {
   "title": "Netz Einspeisung/Bezug",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Einspeisung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "select": [
      [
       {
        "params": [
         "Total active power (powermeter)"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "Total active power (powermeter)",
       "operator": "<",
       "value": "0"
      }
     ]
    },
    {
     "alias": "Bezug",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "select": [
      [
       {
        "params": [
         "Total active power (powermeter)"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "Total active power (powermeter)",
       "operator": ">",
       "value": "0"
      }
     ]
    }
   ]
  },
  {
   "title": "Tägliche Erzeugung",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "alias": "Daily yield",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "select": [
      [
       { "params": [ "Daily yield" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Einspeisung/Bezug pro Tag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "alias": "Einspeisung",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "query": "SELECT sum(\"Total active power (powermeter)\") * -1 / ((24 * 60 * 60) / count(\"Total active power (powermeter)\")) / 24 FROM \"modbus.HoldingRegister\" WHERE (\"Total active power (powermeter)\" < 0) AND $timeFilter GROUP BY time(1d) tz('Europe/Berlin')",
     "select": [
      [
       {
        "params": [
         "Total active power (powermeter)"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/ -1000 * $kWEuro" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "Total active power (powermeter)",
       "operator": "<",
       "value": "0"
      }
     ]
    },
    {
     "alias": "Netzbezug",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "query": "SELECT sum(\"Total active power (powermeter)\") * -1 / ((24 * 60 * 60) / count(\"Total active power (powermeter)\")) / 24 FROM \"modbus.HoldingRegister\" WHERE (\"Total active power (powermeter)\" > 0) AND $timeFilter GROUP BY time(1d) tz('Europe/Berlin')",
     "select": [
      [
       {
        "params": [
         "Total active power (powermeter)"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/ -1000 * $kWEuro" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "Total active power (powermeter)",
       "operator": "<",
       "value": "0"
      }
     ]
    }
   ]
  },
  {
   "title": "Kosten/Einnahmen pro Woche",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "alias": "Ertrag Einspeisung",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "query": "SELECT sum(\"Total active power (powermeter)\") / ((24 * 60 * 60) / count(\"Total active power (powermeter)\")) / 24 / 7 / -1000 * $kWEuroEinspeisung FROM \"modbus.HoldingRegister\" WHERE (\"Total active power (powermeter)\" < 0) AND $timeFilter GROUP BY time(1w) tz('Europe/Berlin')",
     "select": [
      [
       {
        "params": [
         "Total active power (powermeter)"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/ -1000 * $kWEuro" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "Total active power (powermeter)",
       "operator": "<",
       "value": "0"
      }
     ]
    },
    {
     "alias": "Kosten Bezug",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "query": "SELECT sum(\"Total active power (powermeter)\") / ((24 * 60 * 60) / count(\"Total active power (powermeter)\")) / 24 / 7 / -1000 * $kWEuroBezug FROM \"modbus.HoldingRegister\" WHERE (\"Total active power (powermeter)\" > 0) AND $timeFilter GROUP BY time(1w) tz('Europe/Berlin')",
     "select": [
      [
       {
        "params": [
         "Total active power (powermeter)"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/ -1000 * $kWEuro" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "Total active power (powermeter)",
       "operator": "<",
       "value": "0"
      }
     ]
    }
   ]
  }
 ]
}